version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "engprod"
s3_bucket = "samcli021891573713"
s3_prefix = "engprod"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
    "Environment=prod",
    "StackName=engprod", 
    "DomainName=eng.seibtribe.us",
    "HostedZoneId=Z03473042HSYD8BUY4XSL",
    "GitHubToken=",
    "GitHubRepo=georgeseib/engage2",
    "GoogleClientIdParameter=/engprod/oauth/google/client-id",
    "GoogleClientSecretParameter=/engprod/oauth/google/client-secret"
]
