version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "engdev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1l75z8h0vbqdr"
s3_prefix = "engdev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
    "Environment=dev",
    "StackName=engdev", 
    "DomainName=eng.dev.seibtribe.us",
    "HostedZoneId=ZB9TUA073B5SH",
    "GitHubRepo=georgeseib/engage2",
    "GoogleClientIdParameter=/engdev/google/client-id",
    "GoogleClientSecretParameter=/engdev/google/client-secret"
]