version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "eng-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-4qhkoy6cytdp"
s3_prefix = "engagements-test"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
confirm_changeset = false
fail_on_empty_changeset = false
parameter_overrides = "DomainName=eng.test.seibtribe.us HostedZoneId=ZB9TUA073B5SH"
