/**
 * THE BUILD ROOM'S WORDS (docs/design/build-room-batch-2-3, B6): the one place
 * a button or list label is written. Every act has one word; a surface reads
 * it from here and never types the label again. tests/build-room-copy.js fails
 * the build when a retired word (RETIRED, below) comes back.
 *
 * Owner rulings 2026-10-08 that override the mockup:
 *   - A tie re-vote keeps "Vote again"; "Ask again" means edit and re-ask the
 *     whole question.
 *   - "Later" is a list, never a kind in "Claude gets it as" (Do now, Keep in
 *     mind, Ask Claude). The server's `later` kind stays accepted.
 */

export const W = Object.freeze({
  // What Claude is doing (docs/design/build-room-doing): the line itself is Claude's own words.
  helperIs: (t) => `A helper is ${t.charAt(0).toLowerCase()}${t.slice(1)}`,
  doingFromClaude: (time) => `Claude said this at ${time}`,
  doingFromTodo: "From Claude's to-do list",
  steps: 'Steps',
  stepsLast: (text) => `last: ${text}`,
  stepRepeat: (text, n) => `${text}, ${n} times`,
  lastSeen: (ago) => `last seen ${ago}`,
  /** The Stage and the phones say nothing about a paused Claude (copy pass 2026-10-10). */
  hostPicksUp: '',
  forDur: (d) => `for ${d}`,
  soFar: (d) => `${d} so far`,
  decided: 'Decided',
  buildingHint: '',
  // Moving an ask on
  showResults: 'Show results',
  openVoting: 'Open voting',
  /** Send B to Claude · Send the top idea to Claude · Send 3.4 to Claude */
  send: (what) => `Send ${what} to Claude`,
  /** A spoken answer, or no single pick to name. */
  sendPlain: 'Send to Claude',
  sendTopIdea: 'Send the top idea to Claude',
  change: 'Change before sending',
  /** Opens the edit: the whole question is asked again. */
  askAgainEllipsis: 'Ask again…',
  /** A tie: a new vote between the tied options (owner ruling). */
  voteAgain: 'Vote again',
  // The wheel
  spin: 'Spin the wheel',
  spinAgain: 'Spin again',
  // Holding back: one list, Later
  recordOnly: 'Record only',
  saveLater: 'Save for later',
  later: 'Later',
  sendNow: 'Send to Claude now',
  remove: 'Remove',
  undo: 'Undo',
  askRoom: 'Ask the room',
  /** The one What's next move that opens the ask window (copy pass 2026-10-10). */
  askRoomHint: 'A starter, or your own',
  askRoomButton: 'Ask',
  /** The Later list: what each item is, and what it tells the host. */
  ideaTag: 'Idea from the room',
  directionTag: 'Direction for Claude',
  laterNote: 'Claude has not heard these',
  laterEmpty: 'Nothing saved for later.',
  putToVote: (n) => `Put ${n} to a vote`,
  putToAVote: 'Put to a vote',
  ctrlEnterVote: 'Ctrl Enter puts them to a vote',
  finishAsk: 'Finish the open question first',
  nothingFound: (kind, subject) => (kind === 'ideas'
    ? `Ideas found nothing to suggest on "${subject}".`
    : `Research found nothing it could source on "${subject}".`),
  hide: 'Hide',
  opensNewTab: 'opens in a new tab',
  voteAtMost: (n) => `A vote takes at most ${n}`,
  requestsLabel: 'Requests',
  groupResearch: (s) => `Research: ${s}`,
  groupIdeas: (s) => `Ideas: ${s}`,
  fromStep: (a) => `From step: ${a}`,
  fromClaude: 'From Claude',
  fromResearch: "From Claude's research",
  claudeOf: (name) => `${name}'s Claude`,
  fromBuilderClaude: (name) => `From ${name}'s Claude`,
  forAbout: (a) => ` for ${a}`,
  sourceSite: (site) => `Source: ${site}`,
  tickPoint: (t) => `Tick: ${t}`,
  tickAll: (h) => `Tick all: ${h}`,
  takeDownClose: 'The point stays up.',
  roomSentIdeas: (n) => `The room sent ${n} ideas about this point:`,
  pointNotes: Object.freeze({
    shown: 'On the Stage', voting: 'In the vote', queued: 'Highlighted', sent: 'Sent to Claude', later: 'Saved for later',
  }),
  laterHeld: 'Later \u00b7 not sent',
  // The kinds ("Claude gets it as"): three, no Later
  doNow: 'Do now',
  keepInMind: 'Keep in mind',
  askClaude: 'Ask Claude',
  // The Session panel (docs/design/build-room-sidebar; the same words as the other engagements' Players tab)
  players: 'Players',
  settings: 'Settings',
  unlockName: 'Unlock name',
  letThemTakeIt: 'Let them take it',
  lockAgain: 'Lock again',
  bringBack: 'Bring back',
  seeInPlayers: 'See in Players',
  /** The nameless cue on the screens the room sees. */
  askingToTake: (n) => `${n} asking to take a name`,
  nPeopleAsking: (n) => `${n} people are asking to take a name`,
  // The way out, the build
  mainMenu: 'Main menu',
  openBuild: 'Open the build',
  openBuildTab: 'Open the build in a new tab',
  /** "Press Space to show results" — muted words at the left of an action row. */
  spaceTo: (what) => `Press Space to ${what}`,
  ctrlEnterSends: 'Ctrl Enter sends',
  ctrlEnterTitle: 'Ctrl Enter, or Cmd Enter on a Mac, sends it',
  /** The confirmations that replace the hint after a press. */
  resultsUp: 'Results are up',
  votingOpen: 'Voting is open',
  votingAgain: 'The room is voting again',
  /** The line under the Settle board: exactly what Claude will be told. */
  told: (key, label, direction, note = '') => {
    const lead = key === 'ask' ? `Claude will be asked about: "${direction}"` : `Claude will be told, as ${label}: "${direction}"`;
    return note ? `${lead} With it, from the set: "${note}"` : lead;
  },
  /** A question whose set says Later: the press saves it, nothing goes to Claude. */
  toldLater: (direction, note = '') => `Goes to Later: "${direction}". Claude hears nothing yet.${note ? ` With it, from the set: "${note}"` : ''}`,
  savedLater: 'Saved for later',
  /** The steps still to come, as one line. */
  nextSteps: (names) => `Next: ${names.join(' \u00b7 ')}`,
  pickRoomChoice: "Pick the room's choice?",
  pick: (label) => `Pick ${label}`,
  // Talking points (docs/design/build-room-talking-points): the Points tab beside Later
  points: 'Points',
  pointsNew: (n) => `${n} new`,
  roomSeesNone: 'The room sees none of these',
  research: 'Research…',
  ideasAsk: 'Ideas…',
  researchTitle: 'Research',
  ideasTitle: 'Ideas',
  researchLabel: 'What should Claude look up?',
  ideasLabel: 'Ideas about what?',
  researchNote: 'Findings come back here, with sources.',
  ideasNote: 'Four to eight ideas come back here.',
  claudeAway: 'Claude starts when it reconnects.',
  sendToClaudeNow: 'Send to Claude',
  close: 'Close',
  cancel: 'Cancel',
  researching: (subject, who = 'Claude') => `${who} is researching: ${subject}`,
  findingIdeas: (subject, who = 'Claude') => `${who} is finding ideas: ${subject}`,
  requestWaits: (kind, subject) => `${kind === 'ideas' ? 'Ideas' : 'Research'} waits: ${subject}.`,
  pointsFull: (n) => `${n} at most. Remove some first.`,
  pointsEmpty: 'No points yet.',
  /** Tooltips on the two request buttons (Host screen only). */
  researchTip: 'Claude looks it up and cites sources.',
  ideasTip: 'Where the build could go next.',
  showOnStage: 'Show on Stage',
  oneAtATime: 'One point at a time on the Stage',
  sendThese: (n) => `Send these ${n} to Claude`,
  tickRange: 'Tick 2 to 8',
  clear: 'Clear',
  ticked: (n) => `${n} ticked`,
  moreOf: (n, noun) => `${n} more ${noun}`,
  fewer: 'Show fewer',
  tagTalk: 'Talking point',
  tagFinding: 'Finding',
  tagIdea: 'Idea',
  // The point on the Stage
  talkItOver: 'Talk it over',
  takeItDown: 'Take it down',
  /** The Host card's accessible name only; nothing on screen says it any more. */
  pointUp: 'A point is up for the room',
  talkPrompt: 'Talk it over. Send an idea.',
  ideasOnThis: 'Ideas on this',
  nIdeas: (n) => `${n} ${n === 1 ? 'idea' : 'ideas'}`,
  notNow: 'Not now',
  putIdeasToVote: (n) => `Put the ${n} ideas to a vote?`,
  takingDown: 'Taking the point down',
  takeDownEither: 'Either way, the point comes down.',
  // The vote from points (T5), the highlight (T6), the run list (T7), the builder (T8)
  voteQuestion: 'The question',
  voteDefaultPrompt: 'Which should Claude take on next?',
  voteOptionsHead: 'Options',
  voteOptionsNote: 'No names or sources shown.',
  picksEach: 'Picks per person',
  ctrlEnterOpens: 'Ctrl Enter opens voting',
  picksRule: '1 to 5',
  fewerPicks: 'One fewer pick',
  morePicks: 'One more pick',
  closeAskOpenVote: (n) => `Close ask ${n} and open the vote`,
  moveForward: 'Move forward',
  nHighlighted: (n) => `${n} highlighted`,
  roomVotedPicks: (voted, here, picks) => `The room voted ${voted} of ${here} · ${picks} ${picks === 1 ? 'pick' : 'picks'}`,
  highlightNote: 'Claude gets the highlighted ones, in order.',
  highlightTie: (labels, count) => `Tie at the cut: ${labels.join(' and ')}. Both highlighted.`,
  highlightNone: 'Click a row to highlight it.',
  highlightRow: (text) => `Highlight: ${text}`,
  saveRest: 'Save the rest for later',
  workInTurn: 'Work through in turn',
  workNeedsTwo: 'Highlight at least 2 to work through in turn',
  runRefused: 'Finish or stop the current list first',
  savedForLater: (n) => `Saved ${n} for later`,
  votesCount: (n) => `${n} ${n === 1 ? 'vote' : 'votes'}`,
  movedForwardDone: 'Moved forward',
  closeThisVote: 'Close this vote',
  workingThrough: 'Working through',
  runStarted: (a, n) => `${a} of ${n} started`,
  runDoneOf: (a, n) => `${a} of ${n} done`,
  runLabel: 'The run list',
  runStateDone: 'Done',
  runStateOn: 'Claude is on it',
  runStateNext: 'Next',
  runStateSkipped: 'Skipped, to Later',
  claudeIsOnItem: (k) => `Claude is on ${k}.`,
  claudeFinishedItem: (k) => `Claude finished ${k}`,
  claudeLastItem: (k) => `Claude is on ${k}, the last.`,
  nextItem: (k, text) => `Next: ${k} · "${String(text).length > 24 ? `${String(text).slice(0, 24).trimEnd()}…` : text}"`,
  nextShort: (k) => `Next: ${k}`,
  nextWaits: (k) => `Next waits until Claude reports ${k} done`,
  sending: 'Sending\u2026',
  reorderItem: (t) => `Reorder ${t} (arrow keys)`,
  skipItem: (k) => `Skip ${k}`,
  stop: 'Stop',
  reorderNote: 'Skipped items go to Later.',
  claudeSaid: (note) => `Claude: "${note}"`,
  listFinished: (n) => `Worked through all ${n}`,
  listStopped: (done, n) => `Stopped after ${done} of ${n}. The rest are in Later.`,
  hideList: 'Hide',
  confirmEarly: (k, j) => `Claude hasn't finished ${k}. Send ${j} anyway?`,
  confirmEarlyBody: (text, k) => `${k} may be left half done.`,
  waitForClaude: 'Wait for Claude',
  sendAnyway: (j) => `Send ${j} anyway`,
  roomChose: (n) => `${n} the room chose`,
  claudeIsOnOf: (k, n) => `Claude is on ${k} / ${n}`,
  claudeFinishedOf: (k, n) => `Claude finished ${k} / ${n}`,
  claudeIsWorking: (k, n) => `Claude is on ${k} of ${n}`,
  claudeWorkingText: (k, n, text) => `Claude is working on ${k} of ${n}: ${text}`,
  runWatch: 'Watch the big screen.',
  spaceSend: (k) => `Press Space to send ${k}`,
  // The room's side of a point on the Stage
  talkSend: 'Send idea',
  talkIdeaLabel: 'Your idea about this',
  talkIdeaSent: 'Sent to the host.',
  talkHelp: 'The host sees your name.',
  // A builder's lane
  lanePointsNote: 'For your task.',
  researchFor: (t) => `Research for ${t}`,
  ideasFor: (t) => `Ideas for ${t}`,
  forYourTask: 'your task',
  yourPoints: 'Your points',
  yourPointsNote: 'the host chooses what the room sees',
  yourPointsNone: 'Nothing yet.',
  laneResearching: (s) => `Your Claude is researching: ${s}`,
  laneFindingIdeas: (s) => `Your Claude is finding ideas: ${s}`,
  laneWaits: 'Your Claude will start when it reconnects.',
  mineStatus: Object.freeze({
    new: 'With the host', shown: 'Shown to the room', voting: "In the room's vote", queued: 'Chosen by the room', sent: 'Sent to Claude', later: 'Saved for later',
  }),
  sendRequest: 'Send',
  // Copy pass 2026-10-10: host screen header, Claude line, bars
  hintHidden: 'Hidden from the room.',
  hintIdeasSlow: 'Open voting when ideas slow.',
  hintAnswersStop: 'Show results when answers stop.',
  hintVotesStop: 'Show results when votes stop.',
  hintCheckWords: 'Check the words, then send.',
  tipLive: 'Changes arrive live.',
  tipDropped: 'Retries on its own.',
  tipOffline: 'Reconnects when the internet returns.',
  tipSignedOut: 'You come straight back here.',
  signedOut: 'Signed out. Sign in again; nothing is lost.',
  tipAuto: "Claude's questions skip your review.",
  stoppedBefore: (n) => `Claude Code stopped before ${n === 1 ? 'your last direction' : `${n} directions`}.`,
  tipCopyContinue: 'Copy, then paste into Claude Code.',
  copiedPaste: 'Copied. Paste into Claude Code.',
  chipNever: 'Not connected. Open More to connect.',
  chipReady: 'Ready for your direction.',
  chipWorking: 'Working.',
  nothingYet: 'Nothing yet.',
  endedEdit: 'Session ended. You can still edit the report.',
  wrappedUp: 'Claude has wrapped up. Check the report, then end the session.',
  unsentDirection: (n) => `Ask ${n} has an unsent direction. Reopen it to send.`,
  startedTooSoon: 'Started building too soon?',
  tipPreview: 'Claude runs the project and links it here.',
  askedPreview: 'Asked Claude for a preview.',
  logged: (t) => `Logged: ${t}`,
  logPlaceholder: 'An idea, a note, or what the room said',
  actsNow: 'Claude acts on this now.',
  readsNextCheckin: 'Claude reads this when it next checks in.',
  tipBrief: 'Claude rereads this when it changes.',
  keepLands: 'Keep in mind directions land here.',
  // Copy pass 2026-10-10: the open ask, dialogs, queue
  tipEditable: 'Editable until someone answers.',
  picturesIn: 'All pictures are in.',
  opensWhenClose: (n) => `Opens when you close ask ${n}.`,
  hiddenUntilIn: (n) => `Hidden until all ${n} are in.`,
  askedMockups: 'Asked Claude for mockups.',
  noPictureFor: (who) => `No picture for ${who} yet.`,
  offlinePreview: 'Claude is offline. Add a preview URL, or open without.',
  editQuestion: 'Edit question',
  tipWaitsHere: 'Waits here.',
  tipLettersKept: 'Renaming keeps the letter.',
  tieOf: (names) => `A tie: ${names}.`,
  spinsToo: 'The room can spin it. You can too.',
  preferredLine: (pref, why, pick) => `The room preferred ${pref} (${why}). ${pick} goes on record as your pick.`,
  tieRecordLine: (pick, tie) => `${tie} ${pick} goes on record as your pick.`,
  noVotesYet: 'The room has not voted yet.',
  yourPick: (pref) => `Your pick. The room preferred ${pref}.`,
  noSuggestions: 'No ideas yet.',
  addSaid: '+ what the room said',
  saidOutLoud: 'Pick what the room said out loud.',
  buildsFromSentence: (total, here) => `Claude builds from this sentence. ${total} of ${here} answered.`,
  saidOptional: 'What the room said (optional)',
  saidPeopleOptional: 'What people said (optional)',
  tipSavedLater: 'Claude hears nothing.',
  tipMarkAll: 'Marks all as seen.',
  tipSeen: 'Their screen says Seen.',
  tipWall: '20 seconds on the Stage, no name.',
  tipTickAnother: 'Tick another idea.',
  nothingWaiting: 'Nothing waiting.',
  noNames: 'No names shown to the room.',
  askMockupsFirst: 'Ask Claude for mockups first',
  hiddenUntilMockups: 'Hidden until the mockups are in.',
  offlineNoMockups: 'Claude is offline. No mockups.',
  fromTheRoom: 'From the room',
  saveDraft: 'Save as a draft',
  noteForClaudePrivate: 'Note for Claude (private)',
  askedInAsk: (n) => `Asked in ask ${n}.`,
  noReadyQuestions: 'No ready questions. Tag a set build-room.',
  ratingScale: '1 needs work \u00b7 5 great',
  claudeGetsAs: 'Claude gets it as',
  // Copy pass 2026-10-10: Connect, Wrap up, End
  connectIntro: 'Claude Code runs on this laptop and joins the room.',
  installNote: 'Run it in a terminal. Needs Node 18 or later.',
  macAllow: 'If your Mac asks about node, click Allow.',
  tipMacAllow: 'So the room can open the build on this Wi-Fi.',
  newFolder: 'A new folder with git, named for the session.',
  shownOnce: 'Shown once.',
  lostIt: 'Lost it? Mint a new one.',
  alreadyOpen: 'Claude Code already open there? Paste this:',
  keyMinted: (minted, used) => `Key minted ${minted}${used ? `, used ${used}` : ''}. A new key stops it.`,
  oldKeyStops: 'The old key stops at once.',
  makesFolder: (folder) => `Makes ~/build-room/${folder} and connects Claude Code.`,
  runInClaude: 'Run it in Claude Code.',
  runThenRestart: 'Run this, then restart Claude Code.',
  wrapLeadAgent: 'Claude wrote this. It leads the report.',
  wrapLeadRoom: 'What the room built. It leads the report.',
  endBody: 'The room and Claude stop. You can still edit the report.',
  // Copy pass 2026-10-10: the ask path
  tipWheelAll: 'The wheel picks from every option.',
  noRatingsYet: 'No ratings yet.',
  clickToPick: 'Click another option to pick it.',
  tiePickHint: 'Spin the wheel, Vote again, or click one.',
  spinPickHint: 'Spin the wheel, or click one.',
  averageOf5: (avg) => `Average ${avg} of 5`,
  // Copy pass 2026-10-10: Wi-Fi share
  wifiSay: 'Anyone on this Wi-Fi can open the build. Off closes it for all.',
  wifiWaiting: 'Update the plugin, then restart it.',
  wifiQuietHead: 'Nobody has opened it in 2 minutes.',
  wifiQuietBody: 'Guest Wi-Fi often blocks this.',
  wifiTest: 'Test it: scan the QR from another device.',
  tipWifiSame: 'Same Wi-Fi; no mobile data, no VPN.',
  wifiFailsForRoom: 'If it fails for you, it fails for the room. Use screenshots.',
  wifiOffer: 'Anyone on this Wi-Fi can open it. Off any time.',
  wallQrScan: 'Scan the code, or press Open the build.',
  sameWifiOnly: 'Same Wi-Fi only.',
  sameWifi: 'Same Wi-Fi',
  // Copy pass 2026-10-10: Stage decide
  notSent: 'Not sent. Try again.',
  notAsked: 'Not sent. Your question is still here.',
  // Copy pass 2026-10-10: Session panel
  wantsName: 'Another device wants the name',
  tipHandover: (name) => `Let them take it: "The name keeps its ideas and votes." Not now: "${name} stays as they are."`,
  departedNote: 'Their ideas and votes stay in the report.',
  roomMeterNote: 'Off: the Stage shows only the count.',
  autoNote: "On: Claude's questions skip your review.",
  crewNote: 'Up to 8 builders, each with their own Claude.',
  startUndoNote: 'Nothing in the brief is lost.',
  endsForAll: 'Ends it for everyone.',
  // Copy pass 2026-10-10: participant screens
  playerIntro: (title) => `You're building ${title}. Send ideas any time.`,
  votingSoon: 'Voting opens soon.',
  noNamesOnWall: (n) => `No names on the wall. Up to ${n}.`,
  changeUntilClose: 'Change it until voting closes.',
  pickedOf: (n, max) => `${n} of ${max} picked`,
  buildFirst: (n, max) => `What would you build first? ${n} of ${max}`,
  thanksSent: 'Thanks. Sent to the host.',
  builtSoFar: 'Built so far',
  haveALook: 'Have a look',
  unlinked: 'Your Claude was unlinked. Merged work stays.',
  staysInReport: 'Your ideas and votes stay in the report.',
  crewNoPlugin: 'No plugin? Ask the host.',
  crewKeyNote: 'Shown once. Your Claude can push and share, not merge.',
  crewNeeds: 'Needs Claude Code and the repo. One task, your own branch.',
  crewFull: 'The crew is full. You can still react.',
  crewWaiting: 'Type the key into Claude Code on your laptop.',
  crewTwo: 'Two on one task is fine.',
  crewPrivate: 'Private until it is on the wall.',
  // Copy pass 2026-10-10: Build and History screens
  buildSoFar: 'The build so far',
  fullSize: 'Full size \u2197',
  // Plugin update notice 2026-10-10: Host screen only, never the Stage or a device
  pluginOutdated: "Claude's plugin is out of date.",
  pluginUpdate: 'Update',
  pluginDotSr: "Claude's plugin is out of date",
});

/** The three kinds the host may choose. `later` is accepted by the server only. */
export const KIND_WORDS = Object.freeze([W.doNow, W.keepInMind, W.askClaude]);

/**
 * Old words that must not appear as a label anywhere in src/src/buildroom.
 * `enforced` is switched on by the task that replaces the word; until then the
 * check in tests/build-room-copy.js skips it. `prefix` matches a label that
 * starts with the word ("Go with B"). `files` scopes a word to those basenames
 * (Dismiss stays legal in the error bar and the opening's draft).
 */
export const RETIRED = Object.freeze([
  // Enforced: replaced in Task 1 (wheel labels, Main menu, Send icon)
  { word: 'Spin', enforced: true },
  { word: 'Spin instead', enforced: true },
  { word: 'Spin the wheel instead', enforced: true },
  { word: 'Back to the main menu', enforced: true },
  // Task 2: the Host ask path and the Composer
  { word: 'Close and show results', enforced: true, task: 2 },
  { word: 'Show Results', enforced: true, task: 2 },
  { word: 'Go with', prefix: true, enforced: true, task: 2 },
  { word: 'Queue it', enforced: true, task: 2 },
  // Task 3: the Stage
  { word: 'Open the vote', enforced: true, task: 3 },
  { word: 'To Claude:', prefix: true, enforced: true, task: 3 },
  { word: 'Re-ask…', enforced: true, task: 3 },
  { word: 'Open the live build ↗', enforced: true, task: 3 },
  // The Stage dock's "Edit" is now W.change; Edit stays legal elsewhere (notes, the crew board).
  { word: 'Edit', files: ['buildScreens.js', 'BuildStageDecide.jsx'], enforced: true, task: 3 },
  // Task 4: one Later list
  { word: 'Park', prefix: true, enforced: true, task: 4 },
  { word: 'Parked', prefix: true, enforced: true, task: 4 },
  { word: 'Send now', enforced: true, task: 4 },
  { word: 'Dismiss', files: ['BuildLater.jsx'], enforced: true, task: 4 },
  { word: 'For Claude, later', prefix: true, enforced: true, task: 4 },
  // The copy pass (2026-10-10): What's next has ONE ask move, W.askRoom.
  { word: 'Ask the room a starter question', enforced: true, task: 'copy-pass' },
  { word: 'Ask the room something new', enforced: true, task: 'copy-pass' },
]);
