#!/usr/bin/env bash
#
# Build and deploy the Engagements React frontend to the development environment.
#
# Usage:
#   scripts/deploy-frontend-dev.sh
#   AWS_PROFILE=myprofile scripts/deploy-frontend-dev.sh
#
# Reads the target bucket, API URL and WebSocket URL from the CloudFormation
# stack named in samconfig-dev.toml, writes them into public/config.js, builds,
# then uploads. Run scripts/deploy-dev.sh first if the stack does not exist yet.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
FRONTEND_DIR="$PROJECT_ROOT/src"
CONFIG_FILE="$PROJECT_ROOT/samconfig-dev.toml"

export AWS_PROFILE="${AWS_PROFILE:-adfs}"

STACK_NAME="$(grep -E '^\s*stack_name\s*=' "$CONFIG_FILE" | head -1 | sed -E 's/.*=[[:space:]]*"([^"]+)".*/\1/')"
REGION="$(grep -E '^\s*region\s*=' "$CONFIG_FILE" | head -1 | sed -E 's/.*=[[:space:]]*"([^"]+)".*/\1/')"
REGION="${REGION:-us-east-1}"

if [ -z "$STACK_NAME" ]; then
    echo "❌ Error: could not read stack_name from $CONFIG_FILE" >&2
    exit 1
fi

echo "🚀 Deploying Engagements frontend"
echo "   stack:   $STACK_NAME"
echo "   region:  $REGION"
echo "   profile: $AWS_PROFILE"
echo

# Fetch every stack output in one call rather than one call per value.
echo "🔍 Reading stack outputs..."
OUTPUTS_JSON="$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --region "$REGION" \
    --query 'Stacks[0].Outputs' \
    --output json)"

get_output() {
    echo "$OUTPUTS_JSON" | python3 -c "
import json,sys
key = sys.argv[1]
for o in json.load(sys.stdin) or []:
    if o['OutputKey'] == key:
        print(o['OutputValue']); break
" "$1"
}

CLOUDFRONT_URL="$(get_output WebsiteUrl)"
API_URL="$(get_output ApiUrl)"
WS_URL="$(get_output WebSocketUrl)"
BUCKET_NAME="$(get_output StaticSiteBucketName)"
DISTRIBUTION_ID="$(get_output StaticSiteDistributionId)"

for pair in "WebsiteUrl:$CLOUDFRONT_URL" "ApiUrl:$API_URL" "WebSocketUrl:$WS_URL" "StaticSiteBucketName:$BUCKET_NAME"; do
    if [ -z "${pair#*:}" ]; then
        echo "❌ Error: stack output ${pair%%:*} is empty. Has scripts/deploy-dev.sh run?" >&2
        exit 1
    fi
done

echo "   website: $CLOUDFRONT_URL"
echo "   api:     $API_URL"
echo "   ws:      $WS_URL"
echo "   bucket:  $BUCKET_NAME"
echo

cd "$FRONTEND_DIR"

# config.js is deliberately not bundled: it is rewritten per environment and
# served unhashed and uncached, so the same build artifacts can be promoted
# between environments.
echo "📝 Writing public/config.js..."
cat > public/config.js << EOF
// Generated by scripts/deploy-frontend-dev.sh — do not edit by hand.
window.API_BASE = '$API_URL/';
window.WS_URL = '$WS_URL';
window.ENV = 'development';
EOF

echo "🔨 Building..."
npm run build

if [ ! -f dist/index.html ]; then
    echo "❌ Error: build produced no dist/index.html" >&2
    exit 1
fi

# Upload order matters. index.html names the hashed asset files, so the assets
# must already exist when it goes live, and the old assets must survive until
# after it does — otherwise a client loading the page mid-deploy gets an
# index.html pointing at files that are missing on one side or the other.
#
#   1. assets/  — new files, no --delete (old ones stay reachable)
#   2. root     — index.html and config.js, the atomic cutover
#   3. assets/  — prune, now that nothing references the old files
echo "☁️  [1/3] Uploading hashed assets..."
aws s3 sync dist/assets/ "s3://$BUCKET_NAME/assets/" \
    --region "$REGION" \
    --cache-control "public,max-age=31536000,immutable"

echo "☁️  [2/3] Uploading index.html and config.js..."
aws s3 sync dist/ "s3://$BUCKET_NAME/" \
    --region "$REGION" \
    --exclude "assets/*" \
    --cache-control "no-cache"

echo "☁️  [3/3] Pruning superseded assets..."
aws s3 sync dist/assets/ "s3://$BUCKET_NAME/assets/" \
    --region "$REGION" \
    --delete \
    --cache-control "public,max-age=31536000,immutable"

# assets/* is content-hashed and cached for a year at the edge, so it never needs
# invalidating. index.html and config.js are served with caching disabled, but
# invalidate them anyway: it is cheap (well inside the free tier) and removes any
# dependency on the cache policy staying as it is.
if [ -n "$DISTRIBUTION_ID" ]; then
    echo "🔄 Invalidating /index.html and /config.js..."
    aws cloudfront create-invalidation \
        --distribution-id "$DISTRIBUTION_ID" \
        --paths "/index.html" "/config.js" \
        --query 'Invalidation.Id' --output text
else
    echo "⚠️  No StaticSiteDistributionId output found — skipping invalidation."
    echo "    Redeploy the backend stack to add it."
fi

echo
echo "✅ Frontend deployment complete."
echo "🌐 $CLOUDFRONT_URL"
